#!/usr/bin/python3

import cairo, sheet, math
import symbol as s

import test.arc as TA

from sheet import mark

surface, c = sheet.create (8, 20, 20)

x0, y0, x1, y1, α = 10, 2, 18, 17, math.radians (60)

c.move_to (x0, y0)
TA.arc_to (c, x1, y1, α)
c.stroke ()

c.move_to (x0, y0)
TA.arc_to (c, x1, y1, α, True)

c.move_to (1, 7)
s.arc_to (c, 1, 13, math.radians (320))
c.stroke ()

c.move_to (2, 8)
s.mark_to (c, 2, 7, "dot")
s.mark_to (c, 4, 7, "arrow")
s.arc_to (c, 7, 10, math.radians (90))
s.arc_to (c, 4, 13, math.radians (90))
s.mark_to (c, 2, 13, "arrow")

c.move_to (3, 6)
s.mark_to (c, 3, 7, "odot")

s.gate (c, 7.5, 15)
s.gate (c, 7.5, 12, "1")
s.gate (c, 7.5, 9, "=1", False)

s.pnp (c, 7.5, 6)
s.npn (c, 7.5, 3.5)
s.diode (c, 5.0, 4.0)
s.resistor (c, 5.0, 5.0)
s.capasitor (c, 5.0, 6.0)

surface.write_to_png ("proto/symbol-render.png")
